# Site settings
title: Modern Adventuress
author: Jen Myers
email: hello@jenmyers.net

baseurl: "https://modernadventuress.com"
url: "https://modernadventuress.com"
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
permalink: none
